baseurl = "https://tokio.rs"
title = "Tokio"
languageCode = "en-us"
canonifyURLs = "true"
googleAnalytics = "UA-90234741-1"

[params]
tokioDocsURL = "https://docs.rs/tokio/0.1/tokio"
tokioExecutorDocsURL = "https://docs.rs/tokio-executor/0.1/tokio_executor"
tokioIoDocsURL = "https://docs.rs/tokio-io/0.1/tokio_io"
tokioTimerDocsURL = "https://docs.rs/tokio-timer/0.2"
futuresDocsURL = "https://docs.rs/futures/0.1/futures"
coreDocsURL = "https://docs.rs/tokio-core/0.1/tokio_core"
protoDocsURL = "https://tokio-rs.github.io/tokio-proto/tokio_proto"
serviceDocsURL = "https://tokio-rs.github.io/tokio-service/tokio_service"
bytesDocsURL = "https://docs.rs/bytes/0.4/bytes"
