[package]
name = "doc-test"
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
build = "build.rs"
public = false

[dependencies]
futures = "0.3.0"
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
