[package]
name = "doc-test"
version = "0.1.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
mini-redis = { path = "/home/carllerche/Code/tokio-mini-redis" }
tokio = { version = "0.2", features = ["full"] }
bytes = "0.5"
doc-comment = "0.3.3"

[build-dependencies]
glob = "0.3"